//
//  Defaults.swift
//  Patanjali
//
//  Created by SRAVANKUMAR V on 21/03/18.
//  Copyright © 2018 SRAVANKUMAR V. All rights reserved.
//

import Foundation
import UIKit

let IPHONE_4_SCREEN_HEIGHT = 480
let IPHONE_4_SCREEN_WIDTH = 320

let IPHONE_5_SCREEN_HEIGHT = 568 //5S,SE
let IPHONE_6_SCREEN_HEIGHT = 667     //6S, 7
let IPHONE_6PLUS_SCREEN_HEIGHT  = 736 // 6s Plus, 7 Plus

let IPHONE_5_SCREEN_WIDTH  = 320 //5S,SE
let IPHONE_6_SCREEN_WIDTH = 375   //6S, 7
let IPHONE_6PLUS_SCREEN_WIDTH = 414 // 6s Plus, 7 Plus

let IPAD_SCREEN_WIDTH = 768 // 6s Plus, 7 Plus

let SYSTEM_VERSION = UIDevice.current.systemVersion

 let COLORSELECTED  = UIColor(red: 130/255.0, green: 187/255.0, blue: 51/255.0, alpha: 1.0)
let COLOR_SELECTED_ORANGE = UIColor(red: 230/255.0, green: 121/255.0, blue: 55/255.0, alpha: 1.0)
let COLORBACKGROUND_GRAY = UIColor(red: 94/255.0, green: 94/255.0, blue: 94/255.0, alpha: 1.0)
let COLORTEXT_SELECTED_GRAY = UIColor(red: 46/255.0, green: 46/255.0, blue: 46/255.0, alpha: 1.0)
let COLORBACKGROUND_UNSELECTED_GRAY = UIColor(red: 237/255.0, green: 237/255.0, blue: 237/255.0, alpha: 1.0)
let COLORTEXT_GRAY = UIColor(red: 107/255.0, green: 107/255.0, blue: 107/255.0, alpha: 1.0)
let COLOR_REDCOLOR = UIColor(red: 130/255.0, green: 0/255.0, blue: 0/255.0, alpha: 1.0)
let COLOR_GRAY_150 = UIColor(red: 150/255.0, green: 150/255.0, blue: 150/255.0, alpha: 1.0)

let APP_DELEGATE  = UIApplication.shared.delegate as! AppDelegate

let SCREEN_WIDTH  = UIScreen.main.bounds.size.width
let SCREEN_HEIGHT  = UIScreen.main.bounds.size.height

let FONTROBOTO_REGULAR  = "OpenSans-Regular"
let FONTROBOTO_SEMIBOLD = "OpenSans-SemiBold"
let FONTROBOTO_BOLD = "OpenSans-SemiBold"
let FONTROBOTO_THIN = "OpenSans-Light"
let FONTROBOTO_LIGHT = "OpenSans-Light"
let FONTROBOTO_SLAB = "OpenSans-SemiBold"
let FONTROBOTO_ITALIC = "Roboto-Italic"
let FONTROBOTO_THINITALIC = "Roboto-ThinItalic"
let FONTROBOTO_LIGHTITALIC = "Roboto-LightItalic"

let FONTROBOTO_CONDENSED_LIGHT = "RobotoCondensed-Light"
let FONTROBOTO_CONDENSED_REGULAR = "RobotoCondensed-Regular"
let FONTROBOTO_CONDENSED_BOLD = "RobotoCondensed-Bold"

let FONTROBOTO_SLAB_LIGHT = "RobotoSlab-Thin"
let FONTROBOTO_SLAB_REGULAR = "RobotoSlab-Light"
let FONTROBOTO_SLAB_BOLD = "RobotoSlab-Regular"

let FONTOPENSANS_LIGHT = "OpenSans-Light"
let FONTOPENSANS_REGULAR = "OpenSans-Regular"
let FONTOPENSANS_BOLD = "OpenSans-SemiBold"

let PRODUCTCATEGORY_NOTIFICATION = "PRODUCT_CATEGORY_NOTIFICATION"
let PRODUCTCATEGORY_NAME = "PRODUCTCATEGORY_NAME"
let PRODUCTCATEGORY_ID = "PRODUCTCATEGORY_ID"
let PRODUCT_ID = "PRODUCT_ID"
let MALE = "MALE"
let FEMALE = "FEMALE"


//MARK: - SCREEN TYPES -
let SCREEN_TYPES = "SCREEN_TYPES"
let SCREEN_ACCOUNT = "SCREEN_ACCOUNT"
let SCREEN_ORDERS = "SCREEN_ORDERS"
let SCREEN_SETTINGS = "SCREEN_SETTINGS"
let SCREEN_CONTACTUS = "SCREEN_CONTACTUS"
let SCREEN_REGISTARTION = "SCREEN_REGISTARTION"
let SCREEN_LOGIN = "SCREEN_LOGIN"
let SCREEN_ARTICLES = "SCREEN_ARTICLES"
let SCREEN_FAQ = "SCREEN_FAQ"
let SCREEN_LEGAL = "SCREEN_LEGAL"
let SCREEN_ABOUTUS = "SCREEN_ABOUTUS"

//MARK: - SORTING TYPES -
let SORTBY_PRICE = "price"
let SORTBY_CREATEDDATE = "createdDate"
let SORTORDER_LOW_TO_HEIGH = "LOW_TO_HIGH"
let SORTORDER_HEIGH_TO_LOW = "HIGH_TO_LOW"


//MARK: - SETTINGS TYPES -
let IS_LOGIN  = "IS_USER_LOGIN"
let AUTHENTICATION_KEY = "AUTHENTICATIONKEYVALUE"
let USERNAME = "USERNAME"
let EMAIL = "EMAIL"
let MOBILENUMBER = "MOBILENUMBER"
let DEVICETOKEN = "DEVICETOKEN"
let DASHBOARD_RESPONSE = "DASHBOARD_RESPONSE"

let  TERMSANDCONDITIONS = "TermsandConditions"
let  PRIVACYPOLICY = "PrivacyPolicy"
let  ABOUTUS = "AboutUs"

let SETTING_NOTIFICATIONS = "NOTIFICATIONS"
let SETTING_NEWSLETTERS = "NEWSLETTERS"


